require "bundler/gem_tasks"
require "rake/testtask"

# Rake::TestTask.new do |t|
#     t.libs << "test"
#     t.test_files = FileList["test/**/*_test.rb"]
#     t.verbose = true
# end

task :default => [:botborn]

task :botborn do
    ruby "lib/rubotirc.rb"
end
